=== swordapp/swordv3/_compost/site/status.schema.json
{
	"$id": "http://purl.org/net/sword/3.0/types/Status",
	"type": "object",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"properties": {
		"@context": {
			"$id": "/properties/@context",
			"type": "string",
			"title": "The JSON-LD Context for this document",
			"description": "MUST be present.",
			"examples": [
				"https://swordapp.github.io/swordv3/swordv3.jsonld"
			]
		},
		"@id": {
			"$id": "/properties/@id",
			"type": "string",
			"title": "The Object-URL for this document",
			"description": "MUST be present",
			"examples": [
				"http://example.com/object/1"
			]
		},
		"@type": {
			"$id": "/properties/@type",
			"type": "string",
			"title": "JSON-LD identifier for the document type",
			"description": "This field is used to define the type of the document, and in this case should always be 'Status'.  MUST be present.",
			"examples": [
				"Status"
			]
		},
		"eTag": {
			"$id": "/properties/eTag",
			"type": "string",
			"title": "The current ETag for the Object",
			"description": "MUST be present if the repository enforces concurrency control"
		},
		"metadata": {
			"$id": "/properties/metadata",
			"type": "object",
			"title": "Information about the identifier/version of the Object's Metadata",
			"description": "MUST be present.",
			"properties": {
				"@id": {
					"$id": "/properties/metadata/properties/@id",
					"type": "string",
					"title": "The Metadata-URL for this Object",
					"description": "MUST be present",
					"examples": [
						"http://www.myorg.ac.uk/sword3/object1/metadata"
					]
				},
				"eTag": {
					"$id": "/properties/metadata/properties/eTag",
					"type": "string",
					"title": "The ETag for the Metadata",
					"description": "MUST be present if the server supports concurrency control"
				}
			},
			"required" : ["@id"]
		},
		"fileSet": {
			"$id": "/properties/fileSet",
			"type": "object",
			"title": "Information about the identifier/version of the Object's FileSet",
			"description": "MUST be present.",
			"properties": {
				"@id": {
					"$id": "/properties/fileSet/properties/@id",
					"type": "string",
					"title": "The FileSet-URL for this Object",
					"description": "MUST be present.",
					"examples": [
						"http://www.myorg.ac.uk/sword3/object1/fileset"
					]
				},
				"eTag": {
					"$id": "/properties/fileSet/properties/eTag",
					"type": "string",
					"title": "The Etag for the FileSet",
					"description": "MUST be present if the server supports concurrency control"
				}
			},
			"required" : ["@id"]
		},
		"service": {
			"$id": "/properties/service",
			"type": "string",
			"title": "The URL for the service to which this item was deposited (the Service-URL)",
			"description": "MUST be present.  This is the URL from which the client can retrieve information about the settings for the server that are relevant to this item (e.g. max upload sizes, etc)",
			"examples": [
				"http://swordapp.org/deposit/43"
			]
		},
		"state": {
			"$id": "/properties/state",
			"type": "array",
			"title": "List of states that the item is in on the server.",
			"description": "At least one state MUST be present, using the SWORD state vocabulary.  Other states using server-specific vocabularies may also be used alongside.",
			"items": {
				"$id": "/properties/state/items",
				"type": "object",
				"properties": {
					"@id": {
						"$id": "/properties/state/items/properties/@id",
						"type": "string",
						"title": "Identifier for the state.",
						"description": "MUST be present.  At least one such identifier MUST be from the SWORD state vocabulary.",
						"examples": [
							"http://purl.org/net/sword/3.0/state/inProgress"
						]
					},
					"description": {
						"$id": "/properties/state/items/properties/description",
						"type": "string",
						"title": "Human readable description of the state",
						"description": "MAY be present",
						"examples": [
							"the item is currently inProgress"
						]
					}
				},
				"required" : ["@id"]
			}
		},
		"actions": {
			"$id": "/properties/actions",
			"type": "object",
			"title": "Container for the list of actions that are available against the object for the client.",
			"description": "MUST be present",

			"properties": {
				"getMetadata": {
					"$id": "/properties/actions/properties/getMetadata",
					"type": "boolean",
					"title": "Whether the client can issue a request to retrieve the item metadata",
					"description": "MUST be present",
					"examples": [
						true
					]
				},
				"getFiles": {
					"$id": "/properties/actions/properties/getFiles",
					"type": "boolean",
					"title": "Whether the client can issue a request to retrieve any/all files in the item (both Binary Files and Packaged Content)",
					"description": "MUST be present",
					"examples": [
						true
					]
				},
				"appendMetadata": {
					"$id": "/properties/actions/properties/appendMetadata",
					"type": "boolean",
					"title": "Whether the client can issue a request to append the metadata of the item",
					"description": "MUST be present",
					"examples": [
						true
					]
				},
				"appendFiles": {
					"$id": "/properties/actions/properties/appendFiles",
					"type": "boolean",
					"title": "Whether the client can issue a request to append one or more files (individually or via a package) to the item",
					"description": "MUST be present",
					"examples": [
						true
					]
				},
				"replaceMetadata": {
					"$id": "/properties/actions/properties/replaceMetadata",
					"type": "boolean",
					"title": "Whether the client can issue a request to replace the item metadata.",
					"description": "MUST be present",
					"examples": [
						true
					]
				},
				"replaceFiles": {
					"$id": "/properties/actions/properties/replaceFiles",
					"type": "boolean",
					"title": "Whether the client can issue a request to replace files in an item.  This may be a single file or all of the files.",
					"description": "MUST be present",
					"examples": [
						true
					]
				},
				"deleteMetadata": {
					"$id": "/properties/actions/properties/deleteMetadata",
					"type": "boolean",
					"title": "Whether the client can issue a request to delete all the item metadata.",
					"description": "MUST be present",
					"examples": [
						true
					]
				},
				"deleteFiles": {
					"$id": "/properties/actions/properties/deleteFiles",
					"type": "boolean",
					"title": "Whether the client can issue a request to delete files in the item.  This may be a single file or all files.",
					"description": "MUST be present",
					"examples": [
						true
					]
				},
				"deleteObject": {
					"$id": "/properties/actions/properties/deleteObject",
					"type": "boolean",
					"title": "Whether the client can issue a request to delete the entire object.",
					"description": "MUST be present.",
					"examples": [
						true
					]
				}
			},

			"required" : ["getMetadata", "getFiles", "appendMetadata", "appendFiles", "replaceMetadata", "replaceFiles", "deleteMetadata", "deleteFiles", "deleteObject"]
		},
		"lastAction": {
			"$id": "/properties/lastAction",
			"type": "object",
			"title": "Container for information about the last action taken on the object by a client (not necessarily the current client).",
			"description": "SHOULD be present, if appropriate",
			"properties": {
				"timestamp": {
					"$id": "/properties/lastAction/properties/timestamp",
					"type": "string",
					"format": "date-time",
					"title": "When the last action was taken by the client",
					"description": "SHOULD be present"
				},
				"log": {
					"$id": "/properties/lastAction/properties/log",
					"type": "string",
					"title": "Detailed log information about the last action",
					"description": "MAY be present",
					"examples": [
						"description of the event that occurred, with any verbose information"
					]
				},
				"treatment": {
					"$id": "/properties/lastAction/properties/treatment",
					"type": "object",
					"title": "Container for information about the treatment the item received in the last action",
					"description": "MAY be present",
					"properties": {
						"@id": {
							"$id": "/properties/lastAction/properties/treatment/properties/@id",
							"type": "string",
							"title": "URL for information about the treatment the item received",
							"description": "MAY be present",
							"examples": [
								"http://www.myorg.ac.uk/treatment"
							]
						},
						"description": {
							"$id": "/properties/lastAction/properties/treatment/properties/description",
							"type": "string",
							"title": "Description of the treatment the item received",
							"description": "MAY be present",
							"examples": [
								"treatment description"
							]
						}
					}
				}
			}
		},
		"links": {
			"$id": "/properties/links",
			"type": "array",
			"title": "List of link objects referring to the various files, both content and metadata, available on the object",
			"description": "MUST be present if there is one or more links available to the client",
			"items": {
				"$id": "/properties/links/items",
				"type": "object",

				"properties": {
					"@id": {
						"$id": "/properties/links/items/properties/@id",
						"type": "string",
						"title": "The URL of the resource",
						"description": "MUST be present",
						"examples": [
							"http://www.myorg.ac.uk/col1/mydeposit.html"
						]
					},
					"rel": {
						"$id": "/properties/links/items/properties/rel",
						"type": "array",
						"title": "The relationship between the resource and the object.",
						"description": "MUST be present. Note that multiple relationships are supported.",
						"items": {
							"$id": "/properties/links/items/properties/rel/items",
							"type": "string",
							"title": "The relationship type type",
							"default": "",
							"examples": [
								"alternate"
							]
						}
					},
					"contentType": {
						"$id": "/properties/links/items/properties/contentType",
						"type": "string",
						"title": "Content type of the resource",
						"description": "SHOULD be present",
						"examples": [
							"text/html"
						]
					},
					"packaging": {
						"$id": "/properties/links/items/properties/packaging",
						"type": "string",
						"title": "The package format identifier if the resource is a package.",
						"description": "SHOULD, if the resource is a package",
						"examples": [
							"http://purl.org/net/sword/3.0/package/SimpleZip"
						]
					},
					"depositedOn": {
						"$id": "/properties/links/items/properties/depositedOn",
						"type": "string",
						"format": "date-time",
						"title": "Timestamp of when the deposit happened",
						"description": "SHOULD be present if this is an Original Deposit"
					},
					"depositedBy": {
						"$id": "/properties/links/items/properties/depositedBy",
						"type": "string",
						"title": "Identifier for the user that deposited the item",
						"description": "SHOULD be present if this is an Original Deposit"
					},
					"depositedOnBehalfOf": {
						"$id": "/properties/links/items/properties/depositedOnBehalfOf",
						"type": "string",
						"title": "Identifier for the user that the item was deposited on behalf of.",
						"description": "SHOULD be present if this is an Original Deposit that was done On-Behalf-Of another user"
					},
					"byReference": {
						"$id": "/properties/links/items/properties/byReference",
						"type": "string",
						"title": "The external URL of the location a By-Reference deposit was retrieved from",
						"description": "SHOULD be present if this is an Original Deposit that was deposited By-Reference, or is an active By-Reference deposit",
						"examples": [
							"http://www.otherorg.ac.uk/by-reference/file.zip"
						]
					},
					"status": {
						"$id": "/properties/links/items/properties/status",
						"type": "string",
						"title": "The status of the resource, with regard to ingest.",
						"description": "SHOULD be present.  For example, packaged resources which are still being unpacked and ingested may announce their status here.  Likewise, by-reference deposits may do the same.  MUST be one of the allowed status URIs.  Any associated information to go along with the status, especially if the status is an error, SHOULD be in link[].log.  If no value is provided, the client MUST assume that the item is in the status: http://purl.org/net/sword/3.0/filestate/ingested",
						"examples": [
							"http://purl.org/net/sword/3.0/filestate/ingested"
						]
					},
					"log": {
						"$id": "/properties/links/items/properties/log",
						"type": "string",
						"title": "Any information associated with the deposit that the client should know.",
						"description": "MAY be present",
						"examples": [
							"[any information associated with the deposit that the client should know]"
						]
					},
					"derivedFrom": {
						"$id": "/properties/links/items/properties/derivedFrom",
						"type": "string",
						"title": "Reference to URL of resource from which the current resource was derived, for example, if extracted from a package that was deposited.",
						"description": "SHOULD be present, if the resource is derived from another resource",
						"examples": [
							"http://www.myorg.ac.uk/sword3/object1/package.zip"
						]
					},
					"dcterms:relation": {
						"$id": "/properties/links/items/properties/dcterms:relation",
						"type": "string",
						"title": "URL to a non-sword access point to the file",
						"description": "MAY be present.  For example, the URL from which an end-user would download the file via the website.  This related URL does not need to support any of the SWORD protocol operations, and indeed may even be on a server or application which has no sword support.  Primary use case is to redirect the user to the web front end for the repository.",
						"examples": [
							"http://www.myorg.ac.uk/repo/123456789/file1.pdf"
						]
					},
					"dcterms:replaces": {
						"$id": "/properties/links/items/properties/dcterms:replaces",
						"type": "string",
						"title": "URL to an older version of the file in the same Object, if this is also present as a resource.",
						"description": "SHOULD be present, if an older version of the file is present",
						"examples": [
							"http://www.myorg.ac.uk/sword3/object1/versions/file1.1.pdf"
						]
					},
					"eTag": {
						"$id": "/properties/links/items/properties/eTag",
						"type": "string",
						"title": "The eTag of the resource",
						"description": "MUST be present if the server supports concurrency control and the resource is available to the client to modify"
					},
					"dcterms:isReplacedBy": {
						"$id": "/properties/links/items/properties/dcterms:isReplacedBy",
						"type": "string",
						"title": "URL to a newer version of the file in the same Object, if this is present as a resource",
						"description": "SHOULD be present, if newer version is present",
						"examples": [
							"http://www.myorg.ac.uk/sword3/object1/file1.pdf"
						]
					},
					"versionReplacedOn": {
						"$id": "/properties/links/items/properties/versionReplacedOn",
						"type": "string",
						"format": "date-time",
						"title": "Date that the current resource was replaced by a newer resource",
						"description": "SHOULD be present if dcterms:isReplacedBy is present"
					}
				},
				"required" : ["@id", "rel"]
			}
		},
		"forwarding": {
			"$id": "/properties/forwarding",
			"type": "array",
			"title": "List of other locations where the object is available.",
			"description": "MAY be present",
			"items": {
				"$id": "/properties/forwarding/items",
				"type": "object",
				"properties": {
					"@id": {
						"$id": "/properties/forwarding/items/properties/@id",
						"type": "string",
						"title": "The SWORD identifier for the Object in the other system",
						"description": "MAY be present",
						"examples": [
							"http://www.otherorg.ac.uk/sword3/object12"
						]
					},
					"links": {
						"$id": "/properties/forwarding/items/properties/links",
						"type": "array",
						"title": "List of links to the Object as it appears in the other system",
						"description": "MAY be present",
						"items": {
							"$id": "/properties/forwarding/items/properties/links/items",
							"type": "object",
							"properties": {
								"@id": {
									"$id": "/properties/forwarding/items/properties/links/items/properties/@id",
									"type": "string",
									"title": "The URL of a representation of the Object in the other system",
									"description": "MUST be present",
									"examples": [
										"http://www.otherorg.ac.uk/col2/yourdeposit.html"
									]
								},
								"rel": {
									"$id": "/properties/forwarding/items/properties/links/items/properties/rel",
									"type": "array",
									"title": "The relationship to the Object that this URL has",
									"description": "MAY be present",
									"items": {
										"$id": "/properties/forwarding/items/properties/links/items/properties/rel/items",
										"type": "string",
										"title": "The relationship type",
										"default": "",
										"examples": [
											"alternate"
										]
									}
								},
								"contentType": {
									"$id": "/properties/forwarding/items/properties/links/items/properties/contentType",
									"type": "string",
									"title": "The Content Type of the resource",
									"description": "MAY be present",
									"examples": [
										"text/html"
									]
								}
							}
						}
					}
				}
			}
		}
	},

	"required" : ["@context", "@id", "@type", "metadata", "fileSet", "service", "state", "actions"]
}

=== swordapp/swordv3/src/examples/status.json
{
  "@context" : "https://swordapp.github.io/swordv3/swordv3.jsonld",

  "@id" : "http://example.com/object/1",
  "@type" : "Status",
  "eTag" : "...",

  "metadata" : {
    "@id" : "http://www.myorg.ac.uk/sword3/object1/metadata",
    "eTag" : "..."
  },
  "fileSet" : {
    "@id" : "http://www.myorg.ac.uk/sword3/object1/fileset",
    "eTag" : "..."
  },

  "service" : "http://swordapp.org/deposit/43",

  "state" : [
    {
      "@id" : "http://purl.org/net/sword/3.0/state/inProgress",
      "description" : "the item is currently inProgress"
    }
  ],

  "actions" : {
    "getMetadata" : true,
    "getFiles" : true,
    "appendMetadata" : true,
    "appendFiles" : true,
    "replaceMetadata" : true,
    "replaceFiles" : true,
    "deleteMetadata" : true,
    "deleteFiles" : true,
    "deleteObject" : true
  },

  "lastAction" : {
    "timestamp" : "[xsd:dateTime]",
    "log" : "description of the event that occurred, with any verbose information",
    "treatment" : {
      "@id" : "http://www.myorg.ac.uk/treatment",
      "description" : "treatment description"
    }
  },

  "links" : [
    {
      "@id" : "http://www.myorg.ac.uk/col1/mydeposit.html",
      "rel" : ["alternate"],
      "contentType" : "text/html"
    },
    {
      "@id" : "http://www.myorg.ac.uk/sword3/object1/package.zip",
      "rel" : ["http://purl.org/net/sword/3.0/terms/originalDeposit"],
      "contentType" : "application/zip",
      "packaging" : "http://purl.org/net/sword/3.0/package/SimpleZip",
      "depositedOn" : "[timestamp]",
      "depositedBy" : "[user identifier]",
      "depositedOnBehalfOf" : "[user identifier]",
      "byReference" : "http://www.otherorg.ac.uk/by-reference/file.zip",
      "status" : "http://purl.org/net/sword/3.0/filestate/ingested",
      "log" : "[any information associated with the deposit that the client should know]"
    },
	  {
      "@id" : "http://www.myorg.ac.uk/sword3/object1/file1.pdf",
      "rel" : [
        "http://purl.org/net/sword/3.0/terms/fileSetFile",
        "http://purl.org/net/sword/3.0/terms/derivedResource"
      ],
      "contentType" : "application/pdf",
      "derivedFrom" : "http://www.myorg.ac.uk/sword3/object1/package.zip",
      "dcterms:relation" : "http://www.myorg.ac.uk/repo/123456789/file1.pdf",
      "dcterms:replaces" : "http://www.myorg.ac.uk/sword3/object1/versions/file1.1.pdf",
      "methods": ["GET", "PUT", "DELETE"],
      "eTag" : "..."
    },
    {
      "@id" : "http://www.myorg.ac.uk/sword3/object1/package.1.zip",
      "rel" : ["http://purl.org/net/sword/terms/packagedContent"],
      "contentType" : "application/zip",
      "packaging" : "http://purl.org/net/sword/3.0/package/SimpleZip"
    },
    {
      "@id" : "http://www.swordserver.ac.uk/col1/mydeposit/metadata.xml",
      "rel" : ["http://purl.org/net/sword/3.0/terms/formattedMetadata"],
      "contentType" : "text/json",
      "metadataFormat" : "http://purl.org/net/sword/3.0/types/Metadata"
    },
    {
      "@id" : "http://www.myorg.ac.uk/sword3/object1/versions/file1.1.pdf",
      "rel" : ["http://purl.org/net/sword/3.0/terms/derivedResource"],
      "contentType" : "application/pdf",
      "dcterms:isReplacedBy" : "http://www.myorg.ac.uk/sword3/object1/file1.pdf",
      "versionReplacedOn" : "[xsd:dateTime]"
    },
    {
      "@id" : "http://www.myorg.ac.uk/sword3/object1/big.zip",
      "rel" : [
        "http://purl.org/net/sword/3.0/terms/segmentedDeposit",
        "http://purl.org/net/sword/3.0/terms/originalDeposit",
        "http://purl.org/net/sword/3.0/terms/fileSetReplacement"
      ],
      "contentType" : "application/zip",
      "packaging" : "http://purl.org/net/sword/3.0/package/SwordBagIt",
      "depositedOn" : "[xsd:dateTime]",
      "depositedBy" : "[user identifier]",
      "depositedOnBehalfOf" : "[user identifier]",
      "segments" : {
        "received" : [1,2,4],
        "expecting" : [3,5],
        "size" : 10000000,
        "segment_size" : 2000000
      },
      "status" : "http://purl.org/net/sword/3.0/filestate/pending"
    },
    {
      "@id" : "http://www.myorg.ac.uk/sword3/object1/reference.zip",
      "rel" : [
        "http://purl.org/net/sword/3.0/terms/byReferenceDeposit",
        "http://purl.org/net/sword/3.0/terms/originalDeposit",
        "http://purl.org/net/sword/3.0/terms/fileSetFile"
      ],
      "byReference" : "http://www.otherorg.ac.uk/by-reference/file2.zip",
      "log" : "Any information on the download, especially if it failed",
      "methods": ["GET", "PUT", "DELETE"],
      "eTag" : "...",
      "status" : "http://purl.org/net/sword/3.0/filestate/ingested"
    }
  ],

  "forwarding" : [
    {
      "@id" : "http://www.otherorg.ac.uk/sword3/object12",

      "links" : [
        {
          "@id" : "http://www.otherorg.ac.uk/col2/yourdeposit.html",
          "rel" : ["alternate"],
          "contentType" : "text/html"
        }
      ]
    }
  ]
}
